substitutions:
  name: jkbms
  device_description: "Monitor a JK-BMS via UART-TTL"
  external_components_source: components

# ESP32 RX pin must be paired with BMS TX pin and vice-versa

  tx_pin: GPIO16
  rx_pin: GPIO17


esphome:
  name: ${name}
  friendly_name: ESPHome JK-BD6A24S10P
  
  comment: ${device_description}
  project:
    name: "syssi.esphome-jk-bms"
    version: 1.5.0

esp32:
  board: esp32doit-devkit-v1
  framework:
    type: arduino

external_components:
  - source: ${external_components_source}
    refresh: 0s

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esphome-Web-69B804"
    password: "12345678"

captive_portal:

web_server:
  js_include: "./v2/www.js"
  js_url: ""
  version: 2
  ota: false

#ota:

logger:
  level: DEBUG

# If you use Home Assistant please remove this `mqtt` section and uncomment the `api` component!
# The native API has many advantages over MQTT: https://esphome.io/components/api.html#advantages-over-mqtt
#mqtt:
#  broker: !secret mqtt_host
#  username: !secret mqtt_username
#  password: !secret mqtt_password
#  id: mqtt_client

# api:

uart:
  - id: uart_0
    baud_rate: 115200
    rx_buffer_size: 384
    tx_pin: ${tx_pin}
    rx_pin: ${rx_pin}

jk_modbus:
  - id: modbus0
    uart_id: uart_0
    rx_timeout: 100ms

jk_bms:
  - id: bms0
    jk_modbus_id: modbus0
    update_interval: 5s


binary_sensor:
  - platform: jk_bms
    balancing:
      name: "${name} balancing"
    balancing_switch:
      name: "${name} balancing switch"
#    charging:
#      name: "${name} charging"
    charging_switch:
      name: "${name} charge MOS"
#    discharging:
#      name: "${name} discharging"
    discharging_switch:
      name: "${name} discharge MOS"
    dedicated_charger_switch:
      name: "${name} Dedicated charger switch"
    online_status:
      name: "${name} Online status"

sensor:
  - platform: jk_bms
    min_cell_voltage:
      name: "${name} Min cell voltage"
    max_cell_voltage:
      name: "${name} Max cell voltage"
    min_voltage_cell:
      name: "${name} Min voltage cell"
    max_voltage_cell:
      name: "${name} Max voltage cell"
    delta_cell_voltage:
      name: "${name} Delta cell voltage"
    average_cell_voltage:
      name: "${name} Avg cell voltage"
    cell_voltage_1:
      name: "${name} Cell voltage 01"
    cell_voltage_2:
      name: "${name} Cell voltage 02"
    cell_voltage_3:
      name: "${name} Cell voltage 03"
    cell_voltage_4:
      name: "${name} Cell voltage 04"
    cell_voltage_5:
      name: "${name} Cell voltage 05"
    cell_voltage_6:
      name: "${name} Cell voltage 06"
    cell_voltage_7:
      name: "${name} Cell voltage 07"
    cell_voltage_8:
      name: "${name} Cell voltage 08"
    cell_voltage_9:
      name: "${name} Cell voltage 09"
    cell_voltage_10:
      name: "${name} Cell voltage 10"
    cell_voltage_11:
      name: "${name} Cell voltage 11"
    cell_voltage_12:
      name: "${name} Cell voltage 12"
    cell_voltage_13:
      name: "${name} Cell voltage 13"
    cell_voltage_14:
      name: "${name} Cell voltage 14"
    cell_voltage_15:
      name: "${name} Cell voltage 15"
    cell_voltage_16:
      name: "${name} Cell voltage 16"

#    cell_voltage_17:
#      name: "${name} cell voltage 17"
#    cell_voltage_18:
#      name: "${name} cell voltage 18"
#    cell_voltage_19:
#      name: "${name} cell voltage 19"
#    cell_voltage_20:
#      name: "${name} cell voltage 20"
#    cell_voltage_21:
#      name: "${name} cell voltage 21"
#    cell_voltage_22:
#      name: "${name} cell voltage 22"
#    cell_voltage_23:
#      name: "${name} cell voltage 23"
#    cell_voltage_24:
#      name: "${name} cell voltage 24"

    power_tube_temperature:
      name: "${name} BMS MOS Temp"
    temperature_sensor_1:
      name: "${name} Battery Temp 1"
    temperature_sensor_2:
      name: "${name} Battery Temp 2"

    total_voltage:
      name: "${name} Battery total voltage"
    current:
      name: "${name} Current"
    power:
      name: "${name} Power"

#    charging_power:
#      name: "${name} charging power"
#    discharging_power:
#      name: "${name} discharging power"

    capacity_remaining:
      name: "${name} capacity remaining"
#    capacity_remaining_derived:
#      name: "${name} capacity remaining Ah"

#    temperature_sensors:
#      name: "${name} temperature sensors"

    charging_cycles:
      name: "${name} charging cycles"
    total_charging_cycle_capacity:
      name: "${name} total charging cycle capacity"
#    battery_strings:
#      name: "${name} battery strings"
    errors_bitmask:
      name: "${name} errors bitmask"
    operation_mode_bitmask:
      name: "${name} operation mode bitmask"

    total_voltage_overvoltage_protection:
      name: "${name} total voltage OVP"
    total_voltage_undervoltage_protection:
      name: "${name} total voltage UVP"

    cell_voltage_overvoltage_protection:
      name: "${name} cell OVP"
    cell_voltage_overvoltage_recovery:
      name: "${name} cell OVP recovery"
    cell_voltage_overvoltage_delay:
      name: "${name} cell OVP delay"

    cell_voltage_undervoltage_protection:
      name: "${name} cell UVP"
    cell_voltage_undervoltage_recovery:
      name: "${name} cell UVP recovery"
    cell_voltage_undervoltage_delay:
      name: "${name} cell UVP delay"


    cell_pressure_difference_protection:
      name: "${name} cell pressure difference protection"
    discharging_overcurrent_protection:
      name: "${name} discharging OCP"
    discharging_overcurrent_delay:
      name: "${name} discharging OCP delay"


    charging_overcurrent_protection:
      name: "${name} charging OCP"
    charging_overcurrent_delay:
      name: "${name} charging OCP delay"
    balance_starting_voltage:
      name: "${name} balance starting voltage"
    balance_opening_pressure_difference:
      name: "${name} balance trigger difference"

#    power_tube_temperature_protection:
#      name: "${name} MOS protection temp"
#    power_tube_temperature_recovery:
#      name: "${name} MOS recovery temp"

    temperature_sensor_temperature_protection:
      name: "${name} NTC protection temp"
    temperature_sensor_temperature_recovery:
      name: "${name} NTC recovery temp"
    temperature_sensor_temperature_difference_protection:
      name: "${name} NTC temp difference protection"

    charging_high_temperature_protection:
      name: "${name} charging high temp protection"
    discharging_high_temperature_protection:
      name: "${name} discharging high temp protection"

    charging_low_temperature_protection:
      name: "${name} charging low temp protection"
    charging_low_temperature_recovery:
      name: "${name} charging low temp recovery"

    discharging_low_temperature_protection:
      name: "${name} discharging low temp protection"
    discharging_low_temperature_recovery:
      name: "${name} discharging low temp recovery"


    total_battery_capacity_setting:
      name: "${name} total battery capacity setting"
    current_calibration:
      name: "${name} current calibration"
    device_address:
      name: "${name} device address"
    sleep_wait_time:
      name: "${name} sleep wait time"
    alarm_low_volume:
      name: "${name} alarm low volume"
    manufacturing_date:
      name: "${name} manufacturing date"
    total_runtime:
      name: "${name} runtime hours"
    start_current_calibration:
      name: "${name} start current calibration"
#    actual_battery_capacity:
#      name: "${name} actual battery capacity"
#    protocol_version:
#      name: "${name} protocol version"

text_sensor:
  - platform: jk_bms
    errors:
      name: "${name} errors"
    operation_mode:
      name: "${name} operation mode"
    battery_type:
      name: "${name} battery type"
#    password:
#      name: "${name} password"
    device_type:
      name: "${name} device type"
#    software_version:
#      name: "${name} software version"
    manufacturer:
      name: "${name} USER string"
    total_runtime_formatted:
      name: "${name} runtime days"
